// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaeYMeabie0Zq-Z9z9y6zYprHeUYuBtFI',
    appId: '1:219563756047:web:7280283afabff75f1f317a',
    messagingSenderId: '219563756047',
    projectId: 'scissorsdoctor-33707',
    authDomain: 'scissorsdoctor-33707.firebaseapp.com',
    storageBucket: 'scissorsdoctor-33707.appspot.com',
    measurementId: 'G-2GCFSV700Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHZDqyHF_k6NfDRLm7thNWoIp5-GXVeYc',
    appId: '1:219563756047:android:00d9d51acd5ec7e01f317a',
    messagingSenderId: '219563756047',
    projectId: 'scissorsdoctor-33707',
    storageBucket: 'scissorsdoctor-33707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPaTDIHmfDRg6f-LK-Tu3p2hURQwMyrI',
    appId: '1:219563756047:ios:59e548db5e48102d1f317a',
    messagingSenderId: '219563756047',
    projectId: 'scissorsdoctor-33707',
    storageBucket: 'scissorsdoctor-33707.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPaTDIHmfDRg6f-LK-Tu3p2hURQwMyrI',
    appId: '1:219563756047:ios:59e548db5e48102d1f317a',
    messagingSenderId: '219563756047',
    projectId: 'scissorsdoctor-33707',
    storageBucket: 'scissorsdoctor-33707.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaeYMeabie0Zq-Z9z9y6zYprHeUYuBtFI',
    appId: '1:219563756047:web:7b6d2e9407500dc91f317a',
    messagingSenderId: '219563756047',
    projectId: 'scissorsdoctor-33707',
    authDomain: 'scissorsdoctor-33707.firebaseapp.com',
    storageBucket: 'scissorsdoctor-33707.appspot.com',
    measurementId: 'G-D34HKY91T4',
  );
}
